// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiibyscrrmunkxqzvyer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaWJ5c2Nycm11bmt4cXp2eWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDg0NTYsImV4cCI6MjA2NjM4NDQ1Nn0.jN6v3_kMZLza9B2EH55-rrMITu0ejP3hkt1N7yh8Scc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});